/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConferenceApp: typeof import('./src/components/ConferenceApp.vue')['default']
    NavbarApp: typeof import('./src/components/Layout/NavbarApp.vue')['default']
    RegisterApp: typeof import('./src/components/Auth/RegisterApp.vue')['default']
  }
}
